### ISSUE TITLE
API documentation / play audio

### ISSUE THREAD

**Issue by blueyed** [joidegn/leo-cli#14]
Is Leo's API documented somewhere? (TRANSLATE_URL)
I could not find anything.

It would be nice to have it optionally play the available audio files (pronunciation).

**Comment by joidegn** [comment]
yeah true, that would be very nice. I haven't really worked on leo-cli in a while so not sure anymore. It is definitely not documented anywhere and not really an API, just their internal web-app to server communication.

**Comment by garfieldnate** [comment]
Here's an example of what we get back from the leo API: https://dict.leo.org/dictQuery/m-vocab/ende/query.xml?tolerMode=nof&lp=ende&lang=de&rmWords=off&rmSearch=on&search=zeug&searchLoc=0&resultOrder=basic&multiwordShowSingle=on

It's an XML document. Each of the `pron` elements represents a recording they have for the parent word. For example, `<pron url="dhkQLr4TpJCfHeGsieF5Uw"/>` means that you can retrieve sound from this URL: https://dict.leo.org/media/audio/dhkQLr4TpJCfHeGsieF5Uw.ogg. Overall the implementation would be something like the following:

1. Accept a -s (or whatever) flag for playing sound
2. Send a normal request to Leo and extract a `pron` element representing the word that should be pronounced from Leo's response.
3. Download the sound file into a temp folder.
4. Play the file using whatever program is available for playing OGG files.

Step 4 is the most complicated because the user would not necessarily have an OGG player available in their terminal (I don't think one is available by default on Mac, for instance).
